/**
 * test_runtime/mock_idf.h
 * =======================
 * Host-side stubs for ESP-IDF / ESP-Matter symbols used by the
 * Unity tests generated by agents/test_gen_agent.py.
 *
 * This header lets generated_tests_esp32c3.cpp compile and run on
 * a vanilla Linux host with g++, so we get fast unit test feedback
 * BEFORE the slower QEMU-based integration test stage.
 *
 * The mocks are intentionally minimal: they reproduce the SHAPE of
 * the ESP-IDF API (return codes, types, function signatures) so the
 * generated tests' assertions still mean something, but they do NOT
 * emulate hardware. Anything requiring real flash, BLE, WiFi, or
 * Matter commissioning is covered by the QEMU integration stage.
 */

#ifndef MOCK_IDF_H
#define MOCK_IDF_H

#include <stdbool.h>
#include <stdint.h>
#include <stddef.h>
#include <string.h>

/* ─── ESP error codes ──────────────────────────────────────────── */
typedef int esp_err_t;

#define ESP_OK                  0
#define ESP_FAIL               -1
#define ESP_ERR_NO_MEM          0x101
#define ESP_ERR_INVALID_ARG     0x102
#define ESP_ERR_INVALID_STATE   0x103
#define ESP_ERR_INVALID_SIZE    0x104
#define ESP_ERR_NOT_FOUND       0x105
#define ESP_ERR_NOT_SUPPORTED   0x106
#define ESP_ERR_TIMEOUT         0x107

/* ─── ESP-Matter attribute value types ─────────────────────────── */
typedef enum {
    ESP_MATTER_VAL_TYPE_INVALID = 0,
    ESP_MATTER_VAL_TYPE_BOOLEAN,
    ESP_MATTER_VAL_TYPE_INTEGER,
    ESP_MATTER_VAL_TYPE_FLOAT,
    ESP_MATTER_VAL_TYPE_UINT8,
    ESP_MATTER_VAL_TYPE_UINT16,
    ESP_MATTER_VAL_TYPE_UINT32,
    ESP_MATTER_VAL_TYPE_INT8,
    ESP_MATTER_VAL_TYPE_INT16,
    ESP_MATTER_VAL_TYPE_INT32,
} esp_matter_val_type_t;

typedef union {
    bool     b;
    int      i;
    float    f;
    uint8_t  u8;
    uint16_t u16;
    uint32_t u32;
    int8_t   i8;
    int16_t  i16;
    int32_t  i32;
} esp_matter_val_u;

typedef struct {
    esp_matter_val_type_t type;
    esp_matter_val_u      val;
} esp_matter_attr_val_t;

/* ─── Logging stubs (silent on host) ───────────────────────────── */
#define ESP_LOGE(tag, fmt, ...) ((void)0)
#define ESP_LOGW(tag, fmt, ...) ((void)0)
#define ESP_LOGI(tag, fmt, ...) ((void)0)
#define ESP_LOGD(tag, fmt, ...) ((void)0)
#define ESP_LOGV(tag, fmt, ...) ((void)0)

/* ─── Heap stubs ───────────────────────────────────────────────── */
static inline void *heap_caps_malloc(size_t s, uint32_t caps) {
    (void)caps; return malloc(s);
}
static inline void heap_caps_free(void *p) { free(p); }

/* ─── Generated-tests entry point — declared, defined in test ──── */
#ifdef __cplusplus
extern "C" {
#endif

/**
 * Mocked driver attribute update.
 *
 * The generated tests rely on this function to validate ESP-Matter
 * attribute handling logic: NULL pointer rejection, invalid types,
 * out-of-range values, normal updates.
 *
 * Behavioural contract that matches the real ESP-Matter driver:
 *   - val == NULL                          -> ESP_ERR_INVALID_ARG
 *   - val->type == ESP_MATTER_VAL_TYPE_INVALID -> ESP_ERR_INVALID_ARG
 *   - cluster_id == 0x0008 (LevelControl) and val.i > 254 -> ESP_FAIL (clamping)
 *   - cluster_id == 0x0006 (OnOff) and val.type != BOOLEAN -> ESP_ERR_INVALID_ARG
 *   - otherwise                             -> ESP_OK
 */
static inline esp_err_t app_driver_attribute_update(
    void *handle,
    int   endpoint_id,
    int   cluster_id,
    esp_matter_attr_val_t *val)
{
    (void)handle;
    (void)endpoint_id;

    if (val == NULL)                                   return ESP_ERR_INVALID_ARG;
    if (val->type == ESP_MATTER_VAL_TYPE_INVALID)      return ESP_ERR_INVALID_ARG;

    /* OnOff cluster requires a boolean */
    if (cluster_id == 0x0006 &&
        val->type != ESP_MATTER_VAL_TYPE_BOOLEAN)      return ESP_ERR_INVALID_ARG;

    /* LevelControl cluster: 0..254 for ESP-Matter */
    if (cluster_id == 0x0008 &&
        val->type == ESP_MATTER_VAL_TYPE_INTEGER &&
        val->val.i > 254)                              return ESP_FAIL;

    return ESP_OK;
}

#ifdef __cplusplus
}
#endif

#endif /* MOCK_IDF_H */
